HouseServicePlatform.Web/Areas/Supplier/Controllers/ContractsSupplierController.cs
namespace HouseServicePlatform.Web.Areas.Supplier.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.BindingModels.Supplier.Contracts;
    using Models.DataModels;
    using NToastNotify;
    using System;
    using System.Threading.Tasks;
    using HouseServicePlatform.Services.Shared.ContractsController.Interfaces;

    [Route("contracts")]
    public class ContractsSupplierController : SupplierBaseController
    {
        private readonly IContractsControllerService service;

        public ContractsSupplierController(UserManager<User> userManager, IToastNotification toastNotification, IContractsControllerService service) : base(userManager, toastNotification)
        {
            this.service = service;
        }

        [HttpGet]
        [Route("all")]
        public async Task<IActionResult> AllContractRequests()
        {
            string supplierId = base.GetUserId();

            var allContractRequsts = await this.service.GetAllContractRequestsForSupplierAsync(supplierId);


            return View(allContractRequsts);
        }

        [HttpGet]
        [Route("create/{id?}")]
        public async Task<IActionResult> CreateContract(int id)
        {
            string supplierId = base.GetUserId();

            bool contractIsForThisSupplier = await this.service.ContractIsForThisUserAsync(supplierId, id);

            if (!contractIsForThisSupplier)
            {
                base.AddErrorToastMessage("You cannot confirm this request");

                return RedirectToAction(nameof(Web.Controllers.HomeController.Index), "Home", new { area = string.Empty });

            }

            var contractBindModel = await this.service.GetCreateContractBindModelAsync(supplierId);
            contractBindModel.JobStartDate = DateTime.UtcNow.AddDays(1);
            contractBindModel.JobEndDate = DateTime.UtcNow.AddDays(2);

            return View(contractBindModel);
        }

        [HttpPost]
        [Route("create/{id?}")]
        public async Task<IActionResult> CreateContract(CreateContractBm contractBm)
        {
            string supplierId = base.GetUserId();

            bool contractIsForThisSupplier = await this.service.ContractIsForThisUserAsync(supplierId, contractBm.OfferId);

            bool supplierHasCreatedContract = await this.service.SupplierHasCreatedContract(supplierId, contractBm.OfferId);

            if (!contractIsForThisSupplier)
            {
                base.AddErrorToastMessage("You cannot confirm this request");

                return RedirectToAction(nameof(Web.Controllers.HomeController.Index), "Home", new { area = string.Empty });

            }

            if (supplierHasCreatedContract)
            {
                AddErrorToastMessage("You have allready sent a contract to this client.");
                return RedirectToAction(nameof(AllContractRequests));
            }

            if (!ModelState.IsValid)
            {
                return View(contractBm);
            }

            await this.service.CreateContractAsync(supplierId, contractBm);

            base.AddSuccessToastMessage("You have successfully sent this contract.");

            return RedirectToAction(nameof(AllContractRequests));
        }
    }
}

HouseServicePlatform.Web/Areas/Supplier/Views/ContractsSupplier/AllContractRequests.cshtml
@model ICollection<AllContractRequests>
@{
    ViewData["Title"] = "Requested Contracts From Customers";
}

@if (Model.Any())
{
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <br />
                <div class="panel panel-primary">
                    <div class="panel-heading text-center">
                        <h4>@ViewData["Title"]</h4>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th><i class="fa fa-user" aria-hiden="true"></i> Customer First Name</th>
                                    <th><i class="fa fa-user" aria-hiden="true"></i> Customer Last Name</th>
                                    <th><i class="fa fa-wrench" aria-hidden="true"></i> Service Type</th>
                                    <th><i class="fa fa-header" aria-hidden="true"></i> Job Title</th>
                                    <th><i class="fa fa-handshake-o" aria-hidden="true"></i> Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var contract in Model)
                                {

                                    <tr>
                                        <td>@contract.CustomerFirstName</td>
                                        <td>@contract.CustomerLastName</td>
                                        <td>@contract.JobCategory</td>
                                        <td>@contract.JobTitle</td>


                                        @if (!contract.SupplierHasSentContract)
                                        {
                                            <td>

                                                <a class="btn btn-sm btn-warning" asp-area="Supplier" asp-controller="ContractsSupplier" asp-action="CreateContract" asp-route-id="@contract.OfferId">Create Contract</a>

                                            </td>
                                        }
                                        else
                                        {
                                            <td><h4 class="text-primary">Sent</h4></td>
                                        }

                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                    <div class="panel-footer">
                        Total Contracts Requested: <strong>@Model.Count()</strong>
                        Total Contracts Sent: <strong>@Model.Count(c => c.SupplierHasSentContract)</strong>
                    </div>
                </div>
                <a class="btn btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">Go Back</a>
            </div>
        </div>
    </div>
}
else
{ <div class="jumbotron">
        <h2 class="text-center text-warning">
            You have no contract requests.

        </h2>
        <a class="btn btn-sm btn-primary" asp-area="" asp-controller="Home" asp-action="Index">Go Back</a>
    </div>
}

HouseServicePlatform.Web/Areas/Supplier/Views/ContractsSupplier/CreateContract.cshtml
@model CreateContractBm
@{
    ViewData["Title"] = "Create Contract";
}
<div class="col-lg-12">
    <h4 class="text-center">Create @Model.JobTitle Contract</h4>
</div>
<div class="row">
    <div class="jumbotron">
        <div class="text-center">
            <h3> </h3>
        </div>
        <br />
        <div id="jobInfo">
            <h3>Job Info:</h3>
            <dl class="dl-horizontal">
                <dt>Type Of Job</dt>
                <dd>@Model.JobCategory</dd>
            </dl>
        </div>
        <div id="client">
            <h3>Client:</h3>
            <dl class="dl-horizontal">
                <dt>First Name:</dt>
                <dd>@Model.CustomerFirstName</dd>
                <dt>Last Name:</dt>
                <dd>@Model.CustomerLastName</dd>
                <dt>Phone:</dt>
                <dd>@Model.CustomerPhoneNumber</dd>
                <dt>Email:</dt>
                <dd>@Model.CustomerEmail</dd>
            </dl>
        </div>

        <div id="supplier">
            <h3>Supplier:</h3>
            <dl class="dl-horizontal">
                <dt>First Name:</dt>
                <dd>@Model.SupplierFirstName</dd>
                <dt>Last Name:</dt>
                <dd>@Model.SupplierLastName</dd>
                <dt>Phone:</dt>
                <dd>@Model.SupplierPhoneNumber</dd>
                <dt>Email:</dt>
                <dd>@Model.SupplierEmail</dd>
            </dl>
        </div>

        <div id="address">
            <h3>Job Adress:</h3>
            <dl class="dl-horizontal">
                <dt>Country:</dt>
                <dd>@Model.JobLocation.Country</dd>
                <dt>City:</dt>
                <dd>@Model.JobLocation.City</dd>
                <dt>Neighborhood Name:</dt>
                <dd>@Model.JobLocation.NeighborhoodName</dd>
                <dt>Street Name:</dt>
                <dd>@Model.JobLocation.StreetName</dd>
                <dt>Street Number:</dt>
                <dd>@Model.JobLocation.StreetNumber</dd>
                <dt>Postal Code:</dt>
                <dd>@Model.JobLocation.PostalCode</dd>
            </dl>
        </div>
        <hr />
        <br />
    </div>
</div>
<div class="col-md-12">
    <form asp-action="CreateContract" method="post">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3 text-center">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="form-group">

                            <label asp-for="JobStartDate"></label>
                            <input type="date" id="jobStartDate" asp-for="JobStartDate" class="form-control" />
                            <span asp-validation-for="JobStartDate" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="JobEndDate"></label>
                            <input type="date" id="jobEndDate" asp-for="JobEndDate" class="form-control" />
                            <span asp-validation-for="JobEndDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PricePerHour"></label>
                            <input id="pricePerHour" asp-for="PricePerHour" value="@Model.PricePerHour" class="form-control" onkeyup="calculate()" />
                            <span asp-validation-for="PricePerHour" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="WorkHours"></label>
                            <input id="workHours" asp-for="WorkHours" class="form-control" min="1" max="10" onkeyup="calculate()" />
                            <span asp-validation-for="WorkHours" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="TotalPricePerDay"></label>
                            <input id="totalPrice" asp-for="TotalPricePerDay" class="form-control" />
                            <span asp-validation-for="TotalPricePerDay" class="text-danger"></span>
                        </div>
                        <input type="hidden" name="offerId" value="@Model.OfferId" />
                        <input type="hidden" asp-for="JobTitle" value="@Model.JobTitle" />
                        <button type="submit" class="btn btn-success">Create Contract</button>
                        <a class="btn btn-primary cancel" asp-action="AllContractRequests">Go Back</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    <script src="~/js/calculateContract.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
}