HouseServicePlatform.Web/Areas/Customer/Controllers/ContractsCustomerController.cs
namespace HouseServicePlatform.Web.Areas.Customer.Controllers
{
    using Models.DataModels;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using NToastNotify;
    using System.Threading.Tasks;
    using HouseServicePlatform.Services.Shared.ContractsController.Interfaces;
    using System.Collections.Generic;
    using Models.ViewModels.Customer.Contracts;


    [Route("contracts")]
    public class ContractsCustomerController : CustomerBaseController
    {
        private readonly IContractsControllerService service;

        public ContractsCustomerController(UserManager<User> userManager, IToastNotification toastNotification, IContractsControllerService service) : base(userManager, toastNotification)
        {
            this.service = service;
        }

        [HttpGet]
        [Route("mycontracts")]
        public async Task<IActionResult> All()
        {
            string customerId = base.GetUserId();

            ICollection<AllContracts> contracts = await this.service.GetAllContractsForCustomerAsync(customerId);

            return View(contracts);
        }

        [HttpGet]
        [Route("confirm/{id?}")]
        public async Task<IActionResult> GetContractToConfirm(int id)
        {
            string customerId = base.GetUserId();

            bool customerIsAthorizedForContract = await this.service.CustomerIsAuthortizedForThisContract(customerId, id);

            if (!customerIsAthorizedForContract)
            {
                base.AddErrorToastMessage("You cannot confirm this contract.");

                return RedirectToAction(nameof(All));
            }

            var model = await this.service.GetContractVmForCustomer(customerId, id);

            if (model != null)
            {
                return View(model);

            }

            base.AddErrorToastMessage("You have already confirmed this contract.");

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        [Route("confrim/{id?}")]
        public async Task<IActionResult> ConfirmContract(int id)
        {
            string customerId = base.GetUserId();

            bool customerIsAthorizedForContract = await this.service.CustomerIsAuthortizedForThisContract(customerId, id);

            if (!customerIsAthorizedForContract)
            {
                base.AddErrorToastMessage("You cannot confirm this contract.");

                return RedirectToAction(nameof(All));
            }

            await this.service.ConfirmContract(customerId, id);

            base.AddSuccessToastMessage("You have successfully confirmed this contract.");

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        [Route("details/{id?}")]
        public async Task<IActionResult> DetailsContract(int id)
        {
            string customerId = base.GetUserId();

            bool customerIsAthorizedForContract = await this.service.CustomerIsAuthortizedForThisContract(customerId, id);

            if (!customerIsAthorizedForContract)
            {
                base.AddErrorToastMessage("You cannot see this contract.");

                return RedirectToAction(nameof(All));
            }

            var model = await this.service.ContractDetails(customerId, id);

            return PartialView("_ContractDetails", model);
        }
    }
}

HouseServicePlatform.Web/Areas/Customer/Controllers/JobsController.cs
namespace HouseServicePlatform.Web.Areas.Customer.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.BindingModels.Customers.Jobs;
    using Models.DataModels;
    using Models.ViewModels.Customer.Jobs;
    using NToastNotify;
    using Services.Customer.JobServiceController.Interfaces;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    [Route("jobs")]
    public class JobsController : CustomerBaseController
    {
        private readonly IJobsServiceController service;

        public JobsController(
            IJobsServiceController service,
            UserManager<User> userManager,
            IToastNotification toastNotification) : base(userManager, toastNotification)
        {
            this.service = service;

        }


        [HttpGet]
        [Route("myjobs")]
        public async Task<IActionResult> All()
        {
            string userId = base.GetUserId();

            ICollection<AllJobsVmCustomer> viewModel = await this.service.GetAllJobsAsync(userId);

            return View(viewModel);

        }

        [HttpGet]
        [Route("create")]
        public async Task<IActionResult> CreateJob()
        {
            string userId = base.GetUserId();

            CreateJobBm vieModel = await this.service.GetCreateJoViewModelAsync(userId);

            return View(vieModel);
        }

        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> CreateJob(CreateJobBm bindModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bindModel);
            }

            string userId = base.GetUserId();

            await this.service.CreateJobServiceAsync(bindModel, userId);

            base.AddSuccessToastMessage("You have successfully posted a job.");

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        [Route("edit/{id?}")]
        public async Task<IActionResult> Edit(int id)
        {
            string customerId = base.GetUserId();

            bool customerIsAuthorsOfJob = await this.service.CustomerIsAuthorOfJobAsync(customerId, id);

            if (!customerIsAuthorsOfJob)
            {
                base.AddErrorToastMessage("You cannot edit this job.");
                return RedirectToAction(nameof(All));
            }

            var model = await this.service.EditAsync(id, customerId);

            if (model == null)
            {
                base.AddErrorToastMessage("Jobs taken by supplier cannot be edited.");
                return RedirectToAction(nameof(All));
            }

            return View(model);

        }

        [HttpPost]
        [Route("edit/{id?}")]
        public async Task<IActionResult> Edit(EditJobBm editModel)
        {
            string customerId = base.GetUserId();

            var customerIsAuthorOfJob = await this.service.CustomerIsAuthorOfJobAsync(customerId, editModel.Id);

            if (!customerIsAuthorOfJob)
            {
                base.AddErrorToastMessage("You cannot edit this job.");
                return RedirectToAction(nameof(All));

            }

            if (!ModelState.IsValid)
            {
                return View(editModel);
            }

            await this.service.EditJobAsync(editModel, customerId);

            base.AddSuccessToastMessage($"Sucessfully updated your job {editModel.Title}.");

            return RedirectToAction(nameof(All));

        }

        [HttpGet]
        [Route("delete/{id?}")]
        public async Task<IActionResult> Delete(int id)
        {
            string customerId = base.GetUserId();

            bool customerIsAuthorsOfJob = await this.service.CustomerIsAuthorOfJobAsync(customerId, id);

            if (!customerIsAuthorsOfJob)
            {
                base.AddErrorToastMessage("You cannot delete this job.");
                return RedirectToAction(nameof(All));
            }

            var model = await this.service.GetDeleteJobVmAsync(id, customerId);

            if (model == null)
            {
                base.AddErrorToastMessage("Jobs taken by supplier cannot be deleted.");
                return RedirectToAction(nameof(All));
            }

            return View(model);
        }

        [HttpPost]
        [Route("destory/{id?}")]
        public async Task<IActionResult> Destroy(int id)
        {
            if (id <= 0)
            {
                return BadRequest();
            }

            string customerId = base.GetUserId();

            var customerIsAuthorOfJob = await this.service.CustomerIsAuthorOfJobAsync(customerId, id);

            if (!customerIsAuthorOfJob)
            {
                base.AddErrorToastMessage("You cannot delete this job.");
                return RedirectToAction(nameof(All));
            }

            await this.service.DestroyJobAsync(id, customerId);

            base.AddSuccessToastMessage("Successfully deleted.");

            return RedirectToAction(nameof(All));
        }

    }
}

HouseServicePlatform.Web/Areas/Customer/Controllers/OffersCustomerController.cs
namespace HouseServicePlatform.Web.Areas.Customer.Controllers
{
    using HouseServicePlatform.Services.Shared.OffersController.Interfaces;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.DataModels;
    using Models.ViewModels.Customer.Offers;
    using NToastNotify;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Models.ViewModels.Customer.Contracts;

    [Route("offers")]
    public class OffersCustomerController : CustomerBaseController
    {
        private readonly IOffersControllerService service;


        public OffersCustomerController(
            IOffersControllerService service,
            UserManager<User> userManager,
            IToastNotification toastNotification) : base(userManager, toastNotification)
        {
            this.service = service;
        }

        [HttpGet]
        [Route("all")]
        public async Task<IActionResult> AllOffers()
        {
            string customerId = base.GetUserId();

            User user = await base.GetUserAsync(customerId);

            ICollection<AllOffersCustomerVm> allOfers = await this.service.GetAllOffersForCustomerAsync(user.Id);

            return View(allOfers);

        }

        [HttpGet]
        [Route("details/{id?}")]
        public async Task<IActionResult> DetailsOffer(int id)
        {
            string customerId = base.GetUserId();

            bool customerCanReadOffer = await this.service.CustomerCanReadOfferAsync(id, customerId);

            if (!customerCanReadOffer)
            {
                base.AddErrorToastMessage("You cannot read this offer.");
                return RedirectToAction(nameof(AllOffers));
            }

            OfferCustomerDetails detailOffer = await this.service.GetCustomerOfferDetails(id, customerId);

            return View(detailOffer);
        }

        [HttpGet]
        [Route("requestcontract/{id?}")]
        public async Task<IActionResult> RequestContract(int id)
        {
            string customerId = base.GetUserId();

            bool offerIsForCustomer = await this.service.CustomerCanReadOfferAsync(id, customerId);

            if (!offerIsForCustomer)
            {
                base.AddErrorToastMessage("You cannot send contract request for this offer.");
                return RedirectToAction(nameof(AllOffers));
            }

            RequestContractVm model = await this
                 .service.GetRequestContractVm(id, customerId);

            if (model == null)
            {
                base.AddErrorToastMessage("You have already submited a request.");
                return RedirectToAction(nameof(AllOffers));
            }

            return View(model);

        }

        [HttpPost]
        [Route("requestcontract/{id?}")]
        public async Task<IActionResult> ConfirmRequestContract(int id)
        {
            string customerId = base.GetUserId();

            bool customerCanConfirmContract = await this.service.CustomerCanReadOfferAsync(id, customerId);

            if (!customerCanConfirmContract)
            {
                base.AddErrorToastMessage("You cannot send contract request for this offer.");

                return RedirectToAction(nameof(AllOffers));
            }

            await this.service.ConfirmRequestToSupplier(id, customerId);

            base.AddSuccessToastMessage("Request subbmited successfully.");

            return RedirectToAction(nameof(AllOffers));

        }
    }
}

HouseServicePlatform.Web/Areas/Supplier/Controllers/OffersSupplierController.cs
namespace HouseServicePlatform.Web.Areas.Supplier.Controllers
{
    using Common.Constants;
    using HouseServicePlatform.Services.Shared.OffersController.Interfaces;
    using HouseServicePlatform.Services.Supplier.HomeController.Interfaces;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.BindingModels.Supplier.Offers;
    using Models.DataModels;
    using Models.ViewModels.Supplier.Offers;
    using NToastNotify;
    using System.Collections.Generic;
    using System.Threading.Tasks;


    [Route("offers")]
    public class OffersSupplierController : SupplierBaseController
    {
        private readonly IOffersControllerService service;
        private readonly IHomeControllerService homeJobsService;


        public OffersSupplierController(
            IOffersControllerService service,
            IToastNotification toastNotification,
            UserManager<User> userManager,
            IHomeControllerService homeJobsService) : base(userManager, toastNotification)
        {
            this.service = service;
            this.homeJobsService = homeJobsService;
        }

        [HttpGet]
        [Route("myoffers")]
        public async Task<IActionResult> AllOffers()
        {
            string supplierId = base.GetUserId();

            ICollection<AllOffersSupplierVm> offers = await this.service.GetAllOffersForSupplierAsync(supplierId);

            return View(offers);
        }

        [HttpGet]
        [Route("read/{id?}")]
        public async Task<IActionResult> ReadOffer(int id)
        {
            string supplierId = base.GetUserId();

            bool supplierCanReadOffer = await this.service.SupplierCanReadOfferAsync(id, supplierId);

            if (!supplierCanReadOffer)
            {
                base.AddErrorToastMessage("You cannot read this offer.");
                return RedirectToAction(nameof(AllOffers));
            }

            ReadOffer readOfferModel = await this.service.GetOfferToReadAsync(id, supplierId);

            return View(readOfferModel);

        }

        [HttpGet]
        [Route("create/{id?}")]
        public async Task<IActionResult> CreateOffer(int id)
        {
            bool jobExists = await this.homeJobsService.JobExists(id);

            if (!jobExists)
            {
                base.AddErrorToastMessage("Job not found.");
                return RedirectToAction(nameof(HomeController.AllJobs), "Home", new { area = WebConstants.SupplierArea });
            }


            bool offerIsAlreadySended = await this.service.IsOfferAlreadySendedAsync(id);

            if (offerIsAlreadySended)
            {
                base.AddErrorToastMessage("You have already submitted an offer to this client.");

                return RedirectToAction(nameof(HomeController.AllJobs), "Home", new { area = WebConstants.SupplierArea });
            }

            CreateOfferBm model = await this.service.GetCreateOfferVmAsync(id);

            return View(model);
        }

        [HttpPost]
        [Route("create/{id?}")]
        public async Task<IActionResult> CreateOffer(CreateOfferBm offerModel)
        {
            bool jobsExists = await this.homeJobsService.JobExists(offerModel.jobId);

            if (!jobsExists)
            {
                base.AddErrorToastMessage("Job not found.");

                return RedirectToAction(nameof(HomeController.AllJobs), "Home", new { area = WebConstants.SupplierArea });
            }

            string supplierId = base.GetUserId();

            User supplier = await base.GetUserAsync(supplierId);

            if (!ModelState.IsValid)
            {
                return View(offerModel);
            }

            await this.service.CreateOfferAsync(supplierId, supplier, offerModel);

            base.AddSuccessToastMessage("Offer successfully sent.");

            return RedirectToAction(nameof(HomeController.AllJobs), "Home", new { area = WebConstants.SupplierArea });

        }
    }
}

HouseServicePlatform.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - House Services</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/toastr/dist/css/toastr.css" />
        <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/index.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Landing"><i class="fa fa-home" aria-hidden="true"></i></a>
            </div>


            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.IsInRole(WebConstants.CustomerRole))
                    {
                        @*<li><a asp-area="Customer" asp-controller="Jobs" asp-action="CreateJob">Add Job</a></li>
                            <li><a asp-area="Customer" asp-controller="Jobs" asp-action="All">My Jobs</a></li>*@

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown"
                               class="dropdown-toggle">Jobs<b class="caret"></b></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a asp-area="Customer" asp-controller="Jobs" asp-action="CreateJob" tabindex="-1">Add Job</a></li>
                                <li><a asp-area="Customer" asp-controller="Jobs" asp-action="All" as tabindex="-1">My Jobs</a></li>
                                @*<li><a tabindex="-1" href="#">Something else here </a></li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1" href="#"> Separated link </a></li>*@
                            </ul>
                        </li>
                        <li><a asp-area="Customer" asp-controller="OffersCustomer" asp-action="AllOffers">Offers</a></li>
                        <li><a asp-area="Customer" asp-controller="ContractsCustomer" asp-action="All">Contracts</a></li>
                    }

                    @if (User.IsInRole(WebConstants.SupplierRole))
                    {
                        <li><a asp-area="Supplier" asp-controller="Home" asp-action="AllJobs">Find Job</a></li>
                        <li><a asp-area="Supplier" asp-controller="OffersSupplier" asp-action="AllOffers">Offers</a></li>
                        <li><a asp-area="Supplier" asp-controller="ContractsSupplier" asp-action="AllContractRequests">Contracts</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <br />
    <div class="container-fluid">
        <div class="row">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p class="text-center">&copy; 2017 - House Services</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/lib/toastr/dist/js/toastr.min.js"></script>



    @await Component.InvokeAsync("NToastNotify.Toastr")

    @RenderSection("Scripts", required: false)
</body>
</html>